apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-crud-app-pvc
  namespace: simple-crud-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-crud-app-config
  namespace: simple-crud-app
data:
  DB_URI: "mongodb://localhost:27017"
